import fs from "fs";
import path from "path";
import { validateDateInput } from "../dateValidation.js";

export interface ReportCleanFileEntry {
  file: string;
  reportDate: string;
  deleted: boolean;
}

export interface ReportCleanResult {
  deleted: number;
  skipped: number;
  totalScanned: number;
  files: ReportCleanFileEntry[];
}

/**
 * Extracts the report date from a timestamped report filename.
 * Filenames are of the form `jsonReport_<ms>.json` or `sheetReport_<ms>.csv`
 * where `<ms>` is a Unix timestamp in milliseconds (from Date.now()).
 * Falls back to the file's mtime when the filename does not match.
 */
function getReportDate(filename: string, filepath: string): Date {
  const match = /^(?:jsonReport|sheetReport)_(\d+)\.(json|csv)$/.exec(filename);
  if (match) {
    const ms = parseInt(match[1], 10);
    if (!isNaN(ms)) return new Date(ms);
  }
  return fs.statSync(filepath).mtime;
}

/**
 * Deletes analyzed report files in `reportsDir` that are older than `beforeDate`.
 *
 * Only targets timestamped `.json` and `.csv` report files generated by the
 * analysis pipeline (`jsonReport_<timestamp>.json`, `sheetReport_<timestamp>.csv`).
 * Stable pointer files (`latest.json`, `latest.csv`) are always skipped.
 *
 * @param beforeDate  ISO date string (YYYY-MM-DD); files with a report date before
 *                    this date are deleted.
 * @param reportsDir  Path to the `AnalyzedReportsFolder`.
 * @param dryRun      When `true`, reports what would be deleted without deleting.
 * @returns Summary of scanned / deleted / skipped files.
 */
export function cleanOldReports(beforeDate: string, reportsDir: string, dryRun = false): ReportCleanResult {
  const before = validateDateInput(beforeDate, "--before-date");
  const files: ReportCleanFileEntry[] = [];
  let deleted = 0;
  let skipped = 0;
  let totalScanned = 0;

  if (!fs.existsSync(reportsDir)) {
    return { deleted, skipped, totalScanned, files };
  }

  const allFiles = fs.readdirSync(reportsDir).filter((f) => {
    // Only handle .json and .csv analyzed report files; skip stable pointer files
    if (f === "latest.json" || f === "latest.csv") return false;
    return f.endsWith(".json") || f.endsWith(".csv");
  });

  for (const filename of allFiles) {
    const filepath = path.join(reportsDir, filename);
    totalScanned++;
    const reportDate = getReportDate(filename, filepath);
    const shouldDelete = reportDate < before;
    const entry: ReportCleanFileEntry = {
      file: filepath,
      reportDate: reportDate.toISOString(),
      deleted: false,
    };

    if (shouldDelete) {
      if (!dryRun) {
        try {
          fs.unlinkSync(filepath);
          entry.deleted = true;
        } catch {
          // skip if cannot delete (e.g. permission error)
        }
      } else {
        entry.deleted = true;
      }
      deleted++;
    } else {
      skipped++;
    }
    files.push(entry);
  }

  return { deleted, skipped, totalScanned, files };
}
